### ISSUE TITLE
Resursively generate files in posts/

### ISSUE THREAD

**Issue by jsav0** [m455/pancake#4]
Is it possible to recursively generate the markdown files in posts/ so we can maintain some hierarchy/categorization of posts by folder name in the output/ directory?
```
posts
├── category1
│   ├── post1.md
│   └── post2.md
├── category2
│   ├── post1.md
│   └── post2.md
└── category3
    ├── post1.md
    └── post2.md
```

```
output
├── category1
│   ├── post1.html
│   └── post2.html
├── category2
│   ├── post1.html
│   └── post2.html
└── category3
    ├── post1.html
    └── post2.html
```

**Comment by m455** [comment]
Hey there, I'm glad to see you were trying out pancake! I made this mostly as my own little personal generator, and don't plan on having categorized post directories right now, but you are definitely more than welcome to fork my project to see if you are able to implement it yourself, if you like!

In the future, if I feel the need to have these categories, I may add them, but right now I've decided to just go with a flat directory structure for this. 

Sorry for any inconveniences this may have caused you!

**Comment by jsav0** [comment]
Thanks for the input. I'm not familiar with racket as a source but I may take a look eventually.
For now, the flat directory structure will do just fine.

I've been playing around with pancake since earlier this morning and happy to report it is working great. 
here is a screenshot of my website in development using pancake:
![image](https://user-images.githubusercontent.com/20546041/87704127-6f4e3780-c78b-11ea-9016-d00feeda9909.png)

**Comment by jsav0** [comment]
Closing issue

**Comment by m455** [comment]
oh my god, you are too kind! i'm so happy you enjoy using it. 

it's weird, i wrote it to fit my niche user requirement of a flat directory structure because i don't have a lot of blog posts, but maybe when i get the motivation/energy to make it produce directory structures, i'll definitely let you know. i'm really sorry about not doing it right now!
